### ISSUE TITLE
rest-server(validatorsets/latest) response speed problem 

### ISSUE THREAD

**Issue by wlsaud619** [e-money/em-ledger#2]
### Summery
Very slow or not loaded when querying "validatorsets/latest" on rest-server

### Network

lilmermaid-3

### Steps to Reproduce
1) ```curl localhost:3317/node_info```
    -> Quick results

2) ```curl localhost:3317/validatorsets/7000```
    -> Quick results

3)  ```curl localhost:3317/validatorsets/latest```
    -> Slow results / **No results(curl: (52) Empty reply from server)**
    -> rest-server log: **duration=42569**

![image](https://user-images.githubusercontent.com/17901095/65226483-e5e5be80-db01-11e9-877a-20047a1a965a.png)

**Comment by mdyring** [comment]
Just an update on this:

Can still be reproduced in lilmermaid-4 works as expected when specifying a prior height:
https://lilmermaid.validator.network/light/validatorsets/145974

Since it works as expected on cosmoshub-3, it could be due to our on-demand block generation?

**Comment by mdyring** [comment]
It seems using the "latest" height waits for a new block to be generated, see https://github.com/tendermint/tendermint/blob/c4ba93a1e6d62b480adb178bb0f9c8d5c6f67717/rpc/core/consensus.go#L56

You'll see the same behavior on cosmoshub-3, where the RPC will not return until after a few seconds (until after the new block is generated).

I'll open an issue on the Tendermint repo for this. 

As a workaround, you can query the /validators RPC (e.g. https://lilmermaid.validator.network/validators) alternatively provide the block height instead of using "latest".
