### ISSUE TITLE
testnet in em-ledger v0.9.6 crashes with Golang 1.16

### ISSUE THREAD

**Issue by blewater** [e-money/em-ledger#77]
**Describe the bug**
em-ledger v0.9.6 (Cosmos Launchpad SDK v0.39.1)

**How to reproduce**
1 Switch to Golang v1.16. You may find this useful https://github.com/moovweb/gvm.
2 mkdir em-ledger-live  # better start fresh
3 git clone git@github.com:e-money/em-ledger.git ./em-ledger-live
4 cd em-ledger-live
5 make local-testnet

**Expected behavior**
Successfully launch the local testnet.

**Screenshots or log output**
```bash
λ make local-testnet
go test -mod=readonly -v --tags="bdd" bdd_test.go localnet_test.go
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0xc000286bf0, 0xc000d600b8, 0x4, 0x8, 0x30, 0x13)
        /usr/local/go/src/crypto/hmac/hmac.go:143 +0x370
....
```
**Additional context**
Our development Stargate version is compatible.
Under investigation whether the SDK v0.39.2 has fixed this issue and whether this is a general SDK issue with the codenamed "Launchpad" releases 0.39.x

**Comment by haasted** [comment]
I did a quick test of whether upgrading the Cosmos-SDK would fix the issue, and it seems to have.

The branch `https://github.com/e-money/em-ledger/tree/upgrade-dep` depends on the v0.39.3 release of the SDK. Upgrading revealed that the test keystore was actually initialized with a completely incorrect hdPath, which caused a crash. That's fixed in the branch as well.

We need to do more testing of whether the upgrade maintains complete compatibility with our current network before doing a bug-fix release.

**Comment by haasted** [comment]
I synced the entire mainnet with the branch mentioned above, without encountering any crashes or issues.

Looks like it's safe to cut a release from the branch.
